# Generated by Django 4.0.3 on 2022-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=4)),
                ('tahun_terbit', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=100)),
                ('durasi', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2000)),
                ('sutradara', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='poster_film/')),
            ],
        ),
    ]
