# Generated by Django 4.0.3 on 2022-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movix_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
